### ISSUE TITLE
Upgrade `jackson-kotlin-module` to `2.14.0` when released

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-gradle-plugin#106]
There is a medium priority vulnerability for Kotlin 1.5.x., this dependency is being brought in transitively through the `jackson-kotlin-module:2.13.2`

We cannot address this issue until there is a new release of jackson.

https://mvnrepository.com/artifact/com.fasterxml.jackson.module/jackson-module-kotlin

**Comment by shanman190** [comment]
Given our use of `latest.release` this is completed. The current plugin is using 2.14.2 at this time.
