### ISSUE TITLE
No fallback for rewrite version

### ISSUE THREAD

**Issue by nomisRev** [openrewrite/rewrite-gradle-plugin#189]
Currently the [rewriteVersion](https://github.com/openrewrite/rewrite-gradle-plugin/blob/f881a23f3339e12c5db16d8446de12167642038a/plugin/src/main/java/org/openrewrite/gradle/ResolveRewriteDependenciesTask.java#L56) results in `null` unless adding `rewrite(platform("org.openrewrite.recipe:rewrite-recipe-bom:1.18.0"))`.

Or should this _version_ somehow be on the classpath through a published recipe jar by including `version.properties`? Such that adding a `rewrite("io:arrow-kt:rewrite-arrow:0.1.0-SNAPSHOT")` dependency results in the `rewriteVersion` to not be `null`?

That was not entirely clear to me, an alternative could also be to fallback to `latest.release` as version when `rewriteVersion` is `null`.

The same applies to `extension.getRewriteKotlinVersion`, `extension.getRewritePythonVersion` & `extension.getRewriteGradleModelVersion`. I'm also not entirely sure how `extension.getJacksonModuleKotlinVersion` gets resolved though 🤔

**Comment by shanman190** [comment]
So the way that this is supposed to work is that we have a `rewriteDependencies` configuration in the plugin build to resolve the specific versions into the jar file under `/rewrite/version.properties`.

https://github.com/openrewrite/rewrite-gradle-plugin/blob/f881a23f3339e12c5db16d8446de12167642038a/plugin/build.gradle.kts#L98-L118
https://github.com/openrewrite/rewrite-gradle-plugin/blob/f881a23f3339e12c5db16d8446de12167642038a/plugin/build.gradle.kts#L161-L186

From here, the plugin loads these versions of the classpath to set the default values for each of the extension properties here:
https://github.com/openrewrite/rewrite-gradle-plugin/blob/f881a23f3339e12c5db16d8446de12167642038a/plugin/src/main/java/org/openrewrite/gradle/RewriteExtension.java#L178-L188

You'll notice that each of the version methods grabs the version out of this file.

**Comment by shanman190** [comment]
This should mean that even your PR shouldn't have failed in the first place because a version is provided for the checkstyle dependency.
https://github.com/openrewrite/rewrite-gradle-plugin/pull/188

If I were to wager a guess, I'm guessing that there is another jar on Gradle's classpath with a `rewrite/version.properties` that is getting loaded instead and doesn't contain the necessary information...

**Comment by madorb** [comment]
@nomisRev do you happen to be using [detekt](https://github.com/detekt/detekt)

I just realized that if i have:
```
plugins {
    id("java-library")
    id("io.gitlab.arturbosch.detekt") version "1.21.0"
    id("org.openrewrite.rewrite") version "5.39.0"
}
```

then detekt will work, but openrewrite will not,  but if i reverse the declaration order between those two - both will work.

**Comment by nomisRev** [comment]
I do but changing the order doesn't seem to affect my project, I have multiple other plugins though.

<img width="407" alt="Screenshot 2023-04-05 at 21 09 54" src="https://user-images.githubusercontent.com/12424668/230181104-2969dc13-b320-410c-b9c3-cf19c23ec9a3.png">

**Comment by shanman190** [comment]
Ok, so it appears that I misspoke earlier slightly. Presently the plugin writes the `versions.properties` to the root of the jar. This is obviously conflicting with other `versions.properties` from other jars. We're working on getting a patch in to move the file to `rewrite/versions.properties`, then will do a patch release.

**Comment by nomisRev** [comment]
@madorb disabling detekt does affect it.

@shanman190, I am not sure if it's related but it seems a recipe jar I am trying to depend on is being mangled and cannot be found.

```console
Execution failed for task ':rewriteResolveDependencies'.
> Could not resolve all dependencies for configuration ':detachedConfiguration5'.
  The project declares repositories, effectively ignoring the repositories you have declared in the settings.
  You can figure out how project repositories are declared by configuring your build to fail on project repositories.
  See https://docs.gradle.org/8.0.2/userguide/declaring_repositories.html#sub:fail_build_on_project_repositories for details.
   > Could not find io:arrow-kt:rewrite-arrow.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/io/arrow-kt/rewrite-arrow/arrow-kt-rewrite-arrow.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :
```

This is for:

```kotlin
rewrite("io:arrow-kt:rewrite-arrow:0.1.0-RC")
```

Which is available at https://repo.maven.apache.org/maven2/io/arrow-kt/rewrite-arrow/1.0.0-RC2/

**Comment by nomisRev** [comment]
Just to confirm @madorb and @shanman190. This was the issue, detekt also has `versions.properties` in the root.

https://github.com/detekt/detekt/blob/2cc03a32b169e0b90236d2246b497c60d195a23d/detekt-gradle-plugin/build.gradle.kts#L133

**Comment by shanman190** [comment]
@nomisRev, is that dependency coordinate valid in your `build.gradle.kts` valid?

From a Gradle standpoint, I would have expected the first colon `io:arrow-kt` to have been a dot `io.arrow-kt`.

**Comment by shanman190** [comment]
So I'm running your sample using a local build of https://github.com/openrewrite/rewrite-gradle-plugin/commit/4170f849cb7cc038a50e6b5fc7a42cc25fd4702c.

After updating your rewrite dependency like so:
```
rewrite("io.arrow-kt:rewrite-arrow:1.0.0-RC")
```

The project is now running through correctly.

**Comment by shanman190** [comment]
@madorb or @nomisRev can you all try out the new release?

**Comment by madorb** [comment]
looks good to me!
