### ISSUE TITLE
Documentation 404

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-gradle-plugin#196]
The lower part of README.md shows:

![image](https://user-images.githubusercontent.com/1366654/235372626-349b7a37-ba72-4abe-85ed-15dbbc006860.png)

The second link is 404: https://docs.openrewrite.org/reference/gradle-plugin-configuration

The homepage does not find "gradle plugin reference":

![image](https://user-images.githubusercontent.com/1366654/235372643-d9a4117d-b39d-48ee-82d0-9dc4c19908b9.png)

(Link: https://docs.openrewrite.org/running-recipes/getting-started?q=gradle+plugin+reference)

Source of the doc still exists: https://github.com/openrewrite/rewrite-docs/blob/master/reference/gradle-plugin-configuration.md

**Comment by timtebeek** [comment]
@mike-solomon Any idea why GitBook doesn't deploy that Gradle plugin reference?
The link on the reference page of the documentation does not resolve to docs, but to GitHub:
https://docs.openrewrite.org/reference links to https://github.com/openrewrite/rewrite-docs/blob/master/reference/gradle-plugin-configuration.md
If we manage to get the deployment of the reference page fixed, then we can also close this issue.
If not we can look at alternatives, such as again using GitHub Pages for deployment of generated plugin documentation.
