### ISSUE TITLE
Add support for datatables

### ISSUE THREAD

**Issue by rpau** [openrewrite/rewrite-gradle-plugin#201]
Background

Datatables is a new openrewrite structure to produce tabular content. However, this is not consumable outside of the Moderne SaaS. This creates confusion in the community when they try to run those recipes and no results are generated.

Acceptance Criteria

The plugin produces a CSV with the datatables content.

**Comment by shanman190** [comment]
@rpau, I could see this being useful for the community as well.

I can kinda see two possible ways to go about this: export all data tables from any active recipe or allow the user to export a set that they define. For the second it could possibly look something like this:

```
rewrite {
    activeDatatables(String...)
}
```

I could see a few ways that we could even potentially support both all and some (ie. Glob match or a boolean switch), if that was so desired.

**Comment by rpau** [comment]
I agree. The way that I see it is to export all data tables into different CSVs without any extra configuration. Then, if `activeDatatables` or `datatables(Datatable(name:String, path: Path)...)` is defined, the behavior is restricted to that configuration.

**Comment by timtebeek** [comment]
Folks looking to export and analyze data tables are best off [using the Moderne CLI](https://docs.moderne.io/user-documentation/getting-started/cli-intro). That then also allows running across multiple projects and aggregating the results, and producing reports with Jupyter through `mod study`. Have a look at the Moderne docs to get started there: https://docs.moderne.io/user-documentation/getting-started/data-tables

**Comment by timtebeek** [comment]
@ryan-hudson recently added data tables to the Maven plugin 🙏🏻 
- https://github.com/openrewrite/rewrite-maven-plugin/pull/751

Might make sense to do the same for the Gradle plugin, based on the work Ryan had earlier done in
- https://github.com/openrewrite/rewrite/pull/4087

**Comment by ryanwalker** [comment]
I opened up a PR to implement data tables: https://github.com/openrewrite/rewrite-gradle-plugin/pull/310
