### ISSUE TITLE
Reduce stacktrace noise in the output when running with info mode

### ISSUE THREAD

**Issue by vlsi** [openrewrite/rewrite-gradle-plugin#240]
## What version of OpenRewrite are you using?

org.openrewrite.rewrite.gradle.plugin:6.4.3

## How are you running OpenRewrite?

```kotlin
plugins {
    id("org.openrewrite.rewrite")
}

dependencies {
    rewrite(platform("org.openrewrite.recipe:rewrite-recipe-bom:2.4.1"))
    rewrite("org.openrewrite.recipe:rewrite-static-analysis")
}

rewrite {
    activeRecipe("org.openrewrite.java.OrderImports")
    activeRecipe("org.openrewrite.staticanalysis.MissingOverrideAnnotation")
}
```

## What is the smallest, simplest way to reproduce the problem?

The project should have files that OpenRewrite can't parse.

## What did you expect to see?

Running the build with `--info` should not be extremely verbose.

## What did you see instead?

Running `./gradlew rewriteRun` produces 187 lines for `pgjdbc/pgjdbc`. There are 52 lines starting with 'There were problems parsing...'

Running the same build with `./gradlew rewriteRun` produces 2 megabyte with 21781 lines.
That makes `--info` virtually unusable.

I suggest that "debugging" openrewrite should be hidden under a special flag as people can rarely deal with OpenRewrite parser failures.

## What is the full stack trace of any errors you encountered?

[rewriteRun.info.txt](https://github.com/openrewrite/rewrite-gradle-plugin/files/13277641/rewriteRun.info.txt)

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

I might probably work on that

A workaround might probably be excluding the problematic files until OpenRewrite parser is fixed.

**Comment by timtebeek** [comment]
That's indeed a lot of output with little in the sense of actionable stack traces. From a spot check a few of those parser errors are related to the issue you've reported:
- https://github.com/openrewrite/rewrite/issues/3667

Our best bet to reduce the output is the resolve those parser errrors, which are rare, in openrewrite/rewrite#3464 as indicated. I suspect you'll then end up with far less output, and are able to narrow down any remaining issues more easily.

That said, if you see any good ways to push some of the current `--info` further down then we're open to (and much appreciate) suggestions!

**Comment by koppor** [comment]
Alternatively, it would be nice if the line number or the concrete issue at "There were problems parsing...". Maybe adding the reason of the exception?

```
2024-08-28T12:33:45.572+0200 [WARN] [org.openrewrite.gradle.isolated.DefaultProjectParser] There were problems parsing src\main\java\org\jabref\logic\ai\chathistory\BibDatabaseChatHistoryManager.java
2024-08-28T12:33:45.572+0200 [DEBUG] [org.openrewrite.gradle.isolated.DefaultProjectParser] java.lang.IllegalStateException: src\main\java\org\jabref\logic\ai\chathistory\BibDatabaseChatHistoryManager.java is not print idempotent.
```

New:


```
2024-08-28T12:33:45.572+0200 [WARN] [org.openrewrite.gradle.isolated.DefaultProjectParser] There were problems at parsing: src\main\java\org\jabref\logic\ai\chathistory\BibDatabaseChatHistoryManager.java is not print idempotent.
```

**Comment by timtebeek** [comment]
For the print idempotence there is not a more specific exception to show, unless we go for the full diff which would inflate the logs again. This recipe should help find any such issues: https://docs.openrewrite.org/recipes/core/findparsefailures

As for the large ouputs as reported on this issue originally I think those have been addressed by the changes to this method since:
- https://github.com/openrewrite/rewrite-gradle-plugin/pull/316
https://github.com/openrewrite/rewrite-gradle-plugin/blob/e1ecb67503e3b0f59fa4f013bb7d76fa3789673a/plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java#L1315-L1323
