### ISSUE TITLE
Allow opt-out from recipe groups

### ISSUE THREAD

**Issue by vlsi** [openrewrite/rewrite-gradle-plugin#243]
## What problem are you trying to solve?

I wanted adding `org.openrewrite.staticanalysis.CodeCleanup` recipe, however, it implies `HideUtilityClassConstructorStyle` which breaks backward compatibility.

## Describe the solution you'd like

I would like to exclude certain rules even if they are included with "group recipe".

## Have you considered any alternatives or workarounds?

An alternative option could probably be adding `boolean isEnabled` at `org.openrewrite.style.Style` level, so the rules could be selectively disabled with `rewrite.yml`

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?

It depends on the preferred implementation

**Comment by timtebeek** [comment]
Thanks for reporting your issue here. It sounds like you want to exclude one recipe when running a composite recipe, is that correct? It comes up from time to time, leading us to add it to the [frequently asked questions](https://docs.openrewrite.org/reference/faq#i-want-to-exclude-a-single-recipe-from-a-collection-of-recipes.). In short it's not easy to exclude a single recipe, as other recipes might expect other recipes to have run already. We suggest you create a copy of such a composite recipe only containing the recipes you want to run.

**Comment by timtebeek** [comment]
Hope you don't mind me closing this issue as there's more details in the link above. I'll still monitor any replies that come in below.

**Comment by vlsi** [comment]
Thanks for the link.
I suggest adding an explicit link from https://docs.openrewrite.org/recipes/staticanalysis/codecleanup and https://docs.openrewrite.org/recipes/staticanalysis/commonstaticanalysis to https://github.com/openrewrite/rewrite-static-analysis/blob/main/src/main/resources/META-INF/rewrite/static-analysis.yml and similar group recipes.

The only practical way of listing 30+ recipes is to copy-paste them, and it would help to reference the relevant source.

**Comment by timtebeek** [comment]
> Thanks for the link. I suggest adding an explicit link from https://docs.openrewrite.org/recipes/staticanalysis/codecleanup and https://docs.openrewrite.org/recipes/staticanalysis/commonstaticanalysis to https://github.com/openrewrite/rewrite-static-analysis/blob/main/src/main/resources/META-INF/rewrite/static-analysis.yml and similar group recipes.
> 
> The only practical way of listing 30+ recipes is to copy-paste them, and it would help to reference the relevant source.

That's what [the GitHub link under Source](https://docs.openrewrite.org/recipes/staticanalysis/codecleanup#source) does right? Or did I misunderstand? Maybe we should add an icon there to make it clear /cc @mike-solomon

**Comment by mike-solomon** [comment]
> > Thanks for the link. I suggest adding an explicit link from https://docs.openrewrite.org/recipes/staticanalysis/codecleanup and https://docs.openrewrite.org/recipes/staticanalysis/commonstaticanalysis to https://github.com/openrewrite/rewrite-static-analysis/blob/main/src/main/resources/META-INF/rewrite/static-analysis.yml and similar group recipes.
> > The only practical way of listing 30+ recipes is to copy-paste them, and it would help to reference the relevant source.
> 
> That's what [the GitHub link under Source](https://docs.openrewrite.org/recipes/staticanalysis/codecleanup#source) does right? Or did I misunderstand? Maybe we should add an icon there to make it clear /cc @mike-solomon Or listing the last element of that path as a clickable link like `FindAndReplace.java` or `static-analysis.yml`

I'm not sure I understand what you're suggesting. Is the idea that we'd want the GitHub logo next to the GitHub link? I'm not sure I follow how that would make the link clearer but maybe I'm misunderstanding something.

**Comment by timtebeek** [comment]
Adding the logo might help indeed, as folks are likely to skip over the text (I know I have in the past).

**Comment by mike-solomon** [comment]
> Adding the logo might help indeed, as folks are likely to skip over the text (I know I have in the past).

Fair enough! [Opened an issue to add that.](https://github.com/openrewrite/rewrite-recipe-markdown-generator/issues/82)

**Comment by vlsi** [comment]
> Adding the logo might help indeed, as folks are likely to skip over the text (I know I have in the past).

I thought the link points to rewrite-docs github, so users could update the docs :-/

**Comment by mike-solomon** [comment]
> > Adding the logo might help indeed, as folks are likely to skip over the text (I know I have in the past).
> 
> I thought the link points to rewrite-docs github, so users could update the docs :-/

Thanks for the feedback and clarification!

Do you think that updating the section to say `Recipe Source` instead of `Source` would make that clearer?

**Comment by vlsi** [comment]
Recepie source would indeed be great!

**Comment by mike-solomon** [comment]
Added a note and updated the title - so hopefully that addresses all the concerns with this. Thanks again for the feedback!

![image](https://github.com/openrewrite/rewrite-gradle-plugin/assets/1187834/3f3b60e3-7b6c-4744-9e10-b12e9ec47316)
