### ISSUE TITLE
rewriteDryRun should have option to show what the actual changes would be, similar to git diff

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite-gradle-plugin#27]
from https://github.com/openrewrite/rewrite-gradle-plugin/pull/25

>`rewriteDryRun`'s existing behavior only prints which files would be changed by which visitors, which isn't very useful. It should instead print what the actual changes would be, similar to what git diff would show you after running rewriteRun/rewriteFix

**Comment by okundzich** [comment]
rewriteDryRun could produce a very long diff if it produces full output rather than a list of files changed. git diff paginates it, but build plugins do not. Maybe leaving existing behaviour is better.

**Comment by aegershman** [comment]
@okundzich I'm okay with leaving this as-is and closing out the issue for the time being if you are.

Conceptually I feel like "dryRun" is more of a way to check "are there any changes available at all?", and those workflows would be better thought about in the context of continuous-integration + automation systems. And in that case, it'd probably be better to have those be their own workflow, and keep `dryRun`'s existing functionality.

In any case I'm content to close this issue for the time being if you all are?
