### ISSUE TITLE
do we have anything for changemanageddependencyandartifactid for gradle?

### ISSUE THREAD

**Issue by Sanskarbajaj** [openrewrite/rewrite-gradle-plugin#278]
org.openrewrite.maven.ChangeManagedDependencyGroupIdAndArtifactId

do we have anything for changemanageddependencyandartifactid for gradle?

**Comment by shanman190** [comment]
`ChangeManagedDependencyGroupIdAndArtifactId` has so far not made any sense for Gradle yet. You're probably looking for `ChangeDependency` which allows you to swap a dependency out.

**Comment by timtebeek** [comment]
You might be interested in this ongoing work, which for now is only in [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions)
- https://github.com/openrewrite/rewrite/pull/4027

Other than that let's continue on Slack, as it's easier to give quick answer there.
