### ISSUE TITLE
GradleProjectParser run method can only be executed once

### ISSUE THREAD

**Issue by blipper** [openrewrite/rewrite-gradle-plugin#283]
## What version of OpenRewrite are you using?
I am using

- Maven/Gradle plugin v6.6.3

## What is the smallest, simplest way to reproduce the problem?
```
@CompileStatic
class InsisterRewriteRunTask extends AbstractRewriteTask {
     public InsisterRewriteRunTask() {
        super();
        setGroup("rewrite");
        setDescription("Apply the active refactoring recipes");
     }

    @TaskAction
    def public void run() {
        logger.info("Hello!")
        RewriteExtension liveExtension = super.extension;
        List<String> activeRecipes = new ArrayList(liveExtension.getActiveRecipes());
        liveExtension.clearActiveRecipes();
        activeRecipes.each {
            logger.info("Running ${it}")
            liveExtension.clearActiveRecipes();
            liveExtension.activeRecipe(it)
            GradleProjectParser myGpp = getProjectParser()
            myGpp.run({throwable -> logger.info("Error during rewrite run", throwable)} as Consumer<Throwable>)
            myGpp.shutdownRewrite();
            this.@gpp = null;
        }
    }
}

```

```
Caused by: org.gradle.api.InvalidUserDataException: Cannot change hierarchy of dependency configuration ':rewriteimplementation' after it has been resolved.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.preventIllegalMutation(DefaultConfiguration.java:1487)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:1459)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.extendsFrom(DefaultConfiguration.java:433)
        at org.openrewrite.gradle.isolated.DefaultProjectParser.parse(DefaultProjectParser.java:695)
```

https://github.com/openrewrite/rewrite-gradle-plugin/blob/v6.6.3/plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java#L693

```
                rewriteImplementation.extendsFrom(implementation);
```

calls extendsFrom to add the config

You cannot change the configuraiton after resolution.

## What did you expect to see?
It should check by calling the getter version of https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.Configuration.html#org.gradle.api.artifacts.Configuration:extendsFrom

## What is the full stack trace of any errors you encountered?
```
```

## Are you interested in [contributing a fix to OpenRewrite]
Yes

**Comment by blipper** [comment]
Added a fix in #284

**Comment by blipper** [comment]
The use case is large enterprise repos which have a state of having many errors at the beginning. I am building a bootstrap mode that will run each recipe at time, apply the fixes, run the build to verify and then commit.  This allows very clear and single atomic commits doing own thing which also allows straightforward rollback if something breaks.

**Comment by timtebeek** [comment]
That's understandable, and thanks for sharing that background. Always good to know how a tool is used to help inform where we might be able to help. We did add a [similar section to the frequently asked question](https://docs.openrewrite.org/reference/faq#is-it-possible-to-apply-recipes-on-a-step-by-step-basis-pausing-after-certain-recipes-so-smaller-com) just this week, but I trust you know what you're doing and are fine with the implications given your context.
