### ISSUE TITLE
Versions not updating in gradle migration recipies

### ISSUE THREAD

**Issue by Sanskarbajaj** [openrewrite/rewrite-gradle-plugin#287]
When we have a Version.gradle file for managing versions that we use in build.gradle 

example 
Version.gradle

springboot-version=2.7.1

build.gradle

springBootVersion=${springboot-version} //from version.gradle file 

then it does not change the version in version.gradle file

**Comment by shanman190** [comment]
@Sanskarbajaj, thanks for this issue. 

At the moment, this is not a supported location. There are two aspects that relate to this:

* The Gradle plugin is strictly only parsing the main build files that are exactly identifiable. (https://github.com/openrewrite/rewrite-gradle-plugin/blob/main/plugin%2Fsrc%2Fmain%2Fjava%2Forg%2Fopenrewrite%2Fgradle%2Fisolated%2FDefaultProjectParser.java#L875-L968)
* The recipes found in `rewrite-gradle` have limited support for global property updating. You might know already, but it is possible to define the version via a property in a rather large amount of places. At one point, I enumerated _some_ of them in a Slack message, but Tim kindly copied that [here](https://github.com/openrewrite/rewrite/pull/3665#issuecomment-1794948186) to keep it beyond the Slack message retention. As you can see from the PR comment though, some places such as an included script in your case are harder than others. Presently, there is support for updating the versions found within the same Gradle script file and `gradle.properties` files.

**Comment by timtebeek** [comment]
This has since been implemented! You should see improvements with the latest snapshot versions. 🎉
