### ISSUE TITLE
Parse function bug

### ISSUE THREAD

**Issue by AnkitaJain06** [openrewrite/rewrite-gradle-plugin#302]
## What version of OpenRewrite are you using?

I am using

- Gradle plugin v6.1.19
## How are you running OpenRewrite?
I am overriding the RewritePlugin to extend some of its functionality.
## What did you see instead?

In DefaultProjectParser.java (org/openrewrite/gradle/isolated/DefaultProjectParser.java)
```java
List<J.CompilationUnit> cus = jp.parse(javaPaths, baseDir, ctx);
```
```
Required type: List <CompilationUnit>
Provided: Stream <SourceFile>
```
The implementation of parse function inside the (org/openrewrite/Parser.class)-
```java
    default Stream<SourceFile> parse(Iterable<Path> sourceFiles, @Nullable Path relativeTo, ExecutionContext ctx) {
        return this.parseInputs((Iterable)StreamSupport.stream(sourceFiles.spliterator(), false).map((sourceFile) -> {
            return new Input(sourceFile, () -> {
                try {
                    return new BufferedInputStream(Files.newInputStream(sourceFile));
                } catch (IOException var2) {
                    throw new UncheckedIOException(var2);
                }
            });
        }).collect(Collectors.toList()), relativeTo, ctx);
    }
```
## What is the full stack trace of any errors you encountered?

```
'java.util.List org.openrewrite.java.JavaParser.parse(java.lang.Iterable, java.nio.file.Path, org.openrewrite.ExecutionContext)'

```

**Comment by shanman190** [comment]
I think you might have misunderstood my statement, so I'll word it a different way.

|rewrite|rewrite-gradle-plugin|Implementation|
|----------|----------|----------|
|7.x|5.x|java.util.List|
|8.x|6.x|java.util.Stream|

The `rewrite-gradle-plugin` repository depends upon `rewrite` 8.x and uses `java.util.Stream` throughout the project. More specifically, nowhere in the 6.x releases does the result of `jp.parse(..)` be assigned to a `java.util.List`. You can see the current implementation here which as well shows the only invocation of `jp.parse(..)` within the current `DefaultProjectParser`. If you notice, the call is within a `flatMap(..)` which furthermore requires the return type to be `java.util.Stream`.
https://github.com/openrewrite/rewrite-gradle-plugin/blob/b0cf73432d948d10bfe29007ae613bdb466da622/plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java#L727

**Comment by shanman190** [comment]
@AnkitaJain06, this appears to be a dependency version bug within your extension and more of a question here in the correct usage of this plugin alongside the rewrite repository. As it seems like I've answered your question now, I'm going to go ahead and close out this ticket now. If there's anything else feel free to open a new issue or reach out in the OpenRewrite Slack workspace `questions` channel.
