### ISSUE TITLE
Gradle 8.x Deprecates PluginConvention and will be Removed in Gradle 9.0

### ISSUE THREAD

**Issue by blipper** [openrewrite/rewrite-gradle-plugin#307]
## What is the smallest, simplest way to reproduce the problem?

This is used in https://github.com/openrewrite/rewrite-gradle-plugin/blob/main/plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java#L103
See 
https://docs.gradle.org/current/userguide/upgrading_version_8.html#deprecated_access_to_conventions

**Comment by shanman190** [comment]
Just noting that there is also a PR for this too.
https://github.com/openrewrite/rewrite-gradle-plugin/pull/299
