### ISSUE TITLE
Revisit recipe runtime classpath contributions

### ISSUE THREAD

**Issue by gadams00** [openrewrite/rewrite-gradle-plugin#31]
Currently, documentation for rewrite-gradle-plugin instructs users to add rewrite recipe dependencies (i.e. rewrite-testing-frameworks) as compileOnly dependencies on the project being mutated. It's not entirely clear why, but compileOnly doesn't work when running rewrite-testing-frameworks with netflix zuul; using implementation scope does work. However, needing to use implementation scoped dependencies is not ideal because it will pollute the application's real dependencies. 2 options were discussed as potential solutions with different benefits.

1. Annotation processor approach: investigate running rewrite as an annotation processor in a gradle build. Rewrite will have access to JCTree objects and could bypass compilation in JavaParser (compilation has already been run before annotation processing). This would support other annotation processors (i.e. lombok), and mixed language projects.
2. Detached configurations. Use gradle detached configuration scopes to strictly control the classpath that's used in the rewrite gradle plugin. The detached configuration we use could extend from compile, so that the projects dependencies would be available, and we'd pick up any recipe jars referred to by the project.

**Comment by sambsnyd** [comment]
@gadams00 I've added a detached configuration called "rewrite" for this purpose. I'll be publishing a patch release and updating the documentation shortly
