### ISSUE TITLE
No longer possible to set active recipe for a recipe that doesn't show up 

### ISSUE THREAD

**Issue by blipper** [openrewrite/rewrite-gradle-plugin#315]
## What version of OpenRewrite are you using?
I am using

-Latest
## How are you running OpenRewrite?
gradle-ish

## What is the smallest, simplest way to reproduce the problem?

```
./gradlew rewriteDiscover

 Task :rewriteDiscover
Available Recipes:
    org.openrewrite.apache.commons.codec.ApacheBase64ToJavaBase64
    org.openrewrite.apache.commons.io.ApacheCommonsFileUtilsRecipes
    org.openrewrite.apache.commons.io.ApacheCommonsFileUtilsRecipes$GetFileRecipe
...

```

https://github.com/openrewrite/rewrite-migrate-java/blob/c1ed883ed98018079dd951fa23877f4362a490b2/src/main/java/org/openrewrite/java/migrate/util/UseMapOf.java#L35

Does not show `org.openrewrite.java.migrate.util.UseMapOf`

## What did you expect to see?

```java
org.openrewrite.java.migrate.util.UseMapOf
```

## What did you see instead?

```java

```

I think the problem is that a change was made recently to require the Recipe to be exposed via an included .yml now instead of searching the jar directly

e.g. https://github.com/search?q=repo%3Aopenrewrite/rewrite-migrate-java%20OptionalNotPresentToIsEmpty&type=code shows up in a yml but does not
https://github.com/search?q=repo%3Aopenrewrite/rewrite-migrate-java%20UseMapOf&type=code

## Are you interested in [contributing a fix to OpenRewrite]
Yes

**Comment by shanman190** [comment]
So I went back a year and the `Environment` is still configured the same, so it will be loading all classes and YAML recipes. 

Did you confirm that rewrite-migrate-java is in your `rewrite` configuration for your local project? It's not a default provided recipe library and specifically needs to be added to the `rewrite` classpath in order for those recipes to be picked up.

**Comment by blipper** [comment]
Sorry.  The recipes were init'ing properly.
