### ISSUE TITLE
Unable to rewrite dependency in build.gradle.kts 

### ISSUE THREAD

**Issue by k3vonk** [openrewrite/rewrite-gradle-plugin#317]
## What version of OpenRewrite are you using?

I am using
- Maven/Gradle plugin v6.20.0
- rewrite-_module_ v1.14.0

## How are you running OpenRewrite?

I am using the Gradle plugin, and my project is a single module project.
```kotlin
plugins {
    kotlin("jvm") version "1.9.24"
    kotlin("plugin.spring") version "1.9.24"
    id("org.springframework.boot") version "3.3.2"
    id("io.spring.dependency-management") version "1.1.6"
    id("org.openrewrite.rewrite") version "6.20.0"
}
```

## What is the smallest, simplest way to reproduce the problem?

Dependency in my `build.gradle.kts` is rewritten

## What did you see instead?

Build succeeded and nothing was rewritten. But when I move my build script to `build.gradle` and rerun, I'm able to see the dependency change. Is this a limitation?

## What is the full stack trace of any errors you encountered?

N/A

**Comment by timtebeek** [comment]
Hi! We're tracking support for .kts files in this existing issue; welcome to subscribe there for updates
- https://github.com/openrewrite/rewrite/issues/3291
