### ISSUE TITLE
gradleParser causes classloading problems when combined with the plugin transformation

### ISSUE THREAD

**Issue by blipper** [openrewrite/rewrite-gradle-plugin#323]
## How are you running OpenRewrite?
Via custom Gradle tasks and isolated classloaders.

## What is the smallest, simplest way to reproduce the problem?
The problem is that rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java is a recipe but lives in the same JAR as 

We override the getResolvedDependencies but this needs is from another classloader so it blows up
https://github.com/openrewrite/rewrite-gradle-plugin/blob/main/plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java#L150

Can we move all of these java recipes to their own JAR so they don't conflict with the OpenRewrite java engine itself?

## What did you see instead?

```
> loader constraint violation: when resolving method 'org.openrewrite.groovy.GroovyParser$Builder org.openrewrite.groovy.GroovyParser$Builder.typeCache(org.openrewrite.java.internal.JavaTypeCache)' the class loader org.openrewrite.gradle.RewriteClassLoader @5e6d03b4 of the current class, org/openrewrite/gradle/isolated/DefaultProjectParser, and the class loader org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader @4a2a073c for the method's defining class, org/openrewrite/groovy/GroovyParser$Builder, have different Class objects for the type org/openrewrite/java/internal/JavaTypeCache used in the signature (org.openrewrite.gradle.isolated.DefaultProjectParser is in unnamed module of loader org.openrewrite.gradle.RewriteClassLoader @5e6d03b4, parent loader org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader @4a2a073c; org.openrewrite.groovy.GroovyParser$Builder is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader @4a2a073c, parent loader org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader @78fef302)
```

## What is the full stack trace of any errors you encountered?

```
stacktrace output here
```

**Comment by blipper** [comment]
The problem is that my plugin is written in gradle/Groovy so the parser loaded automatically.   

I have to do some other funky stuff and extend/replace  because I have a task that runs each recipe one at a time and commit the changes (i.e. A bootstrap mode so all the changes aren't munged together).
```
        Collection<RecipeDescriptor> descriptors = (Collection<RecipeDescriptor>)method.invoke(gpp);
        activeRecipes.each {
            logger.info("Running ${it}")
            liveExtension.clearActiveRecipes();
            liveExtension.activeRecipe(it)
            GradleProjectParser myGpp = getProjectParser()
            myGpp.run({throwable -> logger.info("Error during rewrite run", throwable)} as Consumer<Throwable>)
            myGpp.shutdownRewrite();
            this.@gpp = null;
            if (!isClean(repo)) {
                logger.info("Changes detected.  Will do a dryrun for ${project.name}!");
                brazilBuild()
                String recipeDescriptor = descriptors.findAll {descriptor -> it == descriptor.name}[0].description
                String summary = "Applied ${it}."
                String description = "${recipeDescriptor}.  See https://docs.openrewrite.org/recipes for details. \n\nCleaned by by the TheInsister (https://code.amazon.com/packages/TheInsister)'s `bb rectifyBootstrap`"
                commitChanges(repo, "${summary}\n\n${description}")
                submitCR(project.name, summary, description)
            }
        }
```

**Comment by blipper** [comment]
Ok.  So this is really funky.

The gradle parsing is causing an interaction between the 

https://github.com/openrewrite/rewrite-gradle-plugin/pull/325

The gradle parser is interacting with the plugin build transformer
https://github.com/openrewrite/rewrite-gradle-plugin/blob/main/plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java#L885


https://github.com/gradle/gradle/blob/e893cdfb9810684e429ab1e8f6ee02131291b2ff/platforms/core-runtime/BYTECODE-INTERCEPTION-README.md

**Comment by timtebeek** [comment]
I'm not sure if there's anything left to do here after 
- https://github.com/openrewrite/rewrite-gradle-plugin/pull/325

It seems like the use case here is further removed from the typical use case for the rewrite-gradle-plugin, and not sure we can support that easily. Happy to review any further proposals in PRs, but as an issue this doesn't seem actionable at the moment. Hope you're ok with me closing this issue for that reason.
