### ISSUE TITLE
Rewrite-spring yaml deserialization issue

### ISSUE THREAD

**Issue by gadams00** [openrewrite/rewrite-gradle-plugin#33]
Rewrite-spring recipes RemoveObsoleteRunners and RunnerToExtension are both unable to be deserialized from declarative recipe lists in rewrite-gradle-plugin. We've observed that both contain an `@Option` annotated property that is of type `List<String>`. The exception observed is

```
java.lang.IllegalArgumentException: Could not resolve type id 'org.openrewrite.java.testing.junit5.RemoveObsoleteRunners' as a subtype of `org.openrewrite.Recipe`: no such class found
```
though based on observing the classpath, Recipe and RemoveObsoleteRunners are both definitely present, so we think this exception may be a red herring for the real issue.

**Comment by aegershman** [comment]
Note taking in this issue comment. Will update comment in-place to prevent notification noise. So, ignore this.

---

- can reproduce directly just by simple `rewriteDiscover` (https://github.com/slugstack/slugstack-rewrite-java-definitions/pull/137), though would like to be able to reproduce with test directly
- https://stackoverflow.com/questions/61212915/jackson-invalidtypeidexception-could-not-resolve-type-id-when-deserializing-c
