### ISSUE TITLE
support of gradle version catalogs 

### ISSUE THREAD

**Issue by tompson** [openrewrite/rewrite-gradle-plugin#339]
## What problem are you trying to solve?
I want to be able to use openrewrite in our gradle projects, which are using gradle version catalogs

## Describe the solution you'd like
Gradle version catalogs are defined in settings.gradle - see https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog-declaration - and are very useful for multi module gradle projects.

openrewrite recipes (e.g. for upgrading Spring Boot) do not consider the versions of the dependencies defined in the version catalog

## Additional context
I am not sure if this has to be fixed in the recipes or generally in openrewrite

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?

Yes, I could provide samples or contribute code

**Comment by shanman190** [comment]
Hi @tompson! 👋 

We have an issue tracking TOML support that you can watch here:
https://github.com/openrewrite/rewrite/issues/4400. A member of the community is starting up the toml parser as of yesterday, so progress is starting to be made. Stay tuned for additional updates to come!

As such, I'm going to go ahead and close this issue for now.
