### ISSUE TITLE
6.28.0 Regression: ListUtils.map NoSuchMethodError

### ISSUE THREAD

**Issue by davidh44** [openrewrite/rewrite-gradle-plugin#347]
## What version of OpenRewrite are you using?

Gradle plugin `6.28.0`

## How are you running OpenRewrite?

Running `./gradlew rewriteRun --init-script init.gradle -Drewrite.activeRecipes=software.amazon.awssdk.v2migration.AwsSdkJavaV1ToV2` in unit test

https://github.com/aws/aws-sdk-java-v2/blob/master/test/v2-migration-tests/src/test/java/software/amazon/awssdk/v2migrationtests/GradleProjectTest.java#L99

Pinning to `6.27.2` works

https://github.com/aws/aws-sdk-java-v2/blob/master/test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/gradle/before/init.gradle#L6

## Errors

Runtime error for `NoSuchMethod` on `java.util.List org.openrewrite.internal.ListUtils.map(java.util.List, java.util.function.UnaryOperator)`

```
> Task :rewriteRun FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rewriteRun'.
> java.lang.RuntimeException: Error while visiting test/v2-migration-tests/target/gradle/actual/src/main/java/gradletest/foo/bar/Library.java: java.lang.NoSuchMethodError: 'java.util.List org.openrewrite.internal.ListUtils.map(java.util.List, java.util.function.UnaryOperator)'
    software.amazon.awssdk.v2migration.ChangeSdkType$ChangeTypeVisitor.updateType(ChangeSdkType.java:533)
    software.amazon.awssdk.v2migration.ChangeSdkType$ChangeTypeVisitor.postVisit(ChangeSdkType.java:185)
    software.amazon.awssdk.v2migration.ChangeSdkType$ChangeTypeVisitor.postVisit(ChangeSdkType.java:83)
    org.openrewrite.TreeVisitor.visit(TreeVisitor.java:253)
    org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:320)
    org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1367)
    org.openrewrite.java.JavaVisitor.visitMethodInvocation(JavaVisitor.java:907)

```

**Comment by timtebeek** [comment]
hi! We made a change that is source level compatible, but does require a recompile of your recipe libraries;
- https://github.com/openrewrite/rewrite/pull/4720

We've released all updated versions of all recipe modules that you will want to use together:
 - https://github.com/openrewrite/rewrite-recipe-bom/releases/tag/v2.23.0

**Comment by timtebeek** [comment]
In your case, since you're using Amazon's recipes, you'll want to either pin back to aligned older versions (https://github.com/openrewrite/rewrite-recipe-bom/releases/tag/v2.22.0), or ask them to put out a new release as well.

**Comment by timtebeek** [comment]
Hah; sorry about that; only just now saw that you're the one who did that release 😅 
https://github.com/aws/aws-sdk-java-v2/commit/ba2805da43e450ea5a2aa89a6879c17ffd297e70

**Comment by timtebeek** [comment]
With that I'll close the issue here, as there's not much we can do for you on our end; but I'll monitor replies and happy to help you through if needed.

**Comment by timtebeek** [comment]
Now also fixed in https://github.com/openrewrite/rewrite-recipe-bom/releases/tag/v2.23.1; thanks again!
