### ISSUE TITLE
READ_DATE_TIMESTAMPS_AS_NANOSECONDS when rewrite Spring Boot 2.7 to 3.x

### ISSUE THREAD

**Issue by nicolasb29** [openrewrite/rewrite-gradle-plugin#348]
Hi,

I'm using OpenRewrite to migrate Spring Boot 2.7 to Spring Boot 3.x, like a lot of people I think, but since the version **[6.28.0](https://github.com/openrewrite/rewrite-gradle-plugin/releases/tag/v6.28.0)** I have this error :

`java.lang.RuntimeException: Error while visiting build.gradle: java.lang.NoSuchFieldError: Class com.fasterxml.jackson.annotation.JsonFormat$Feature does not have member field 'com.fasterxml.jackson.annotation.JsonFormat$Feature READ_DATE_TIMESTAMPS_AS_NANOSECONDS'`

I made a project on GitHub to show the problem:

- [URL of the project](https://github.com/nicolasb29/testopenrewritejackson)
- [Output log with the error](https://github.com/nicolasb29/testopenrewritejackson/actions/runs/12074196292/job/33671746482#step:6:2918)
- Rewrite is launch with this command [./gradlew rewriteRun --init-script init.gradle -Drewrite.activeRecipe=org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_0 --info](https://github.com/nicolasb29/testopenrewritejackson/blob/main/.github/workflows/gradle.yml#L41C12-L41C144)

I made a [Gradle dependencies](https://github.com/nicolasb29/testopenrewritejackson/actions/runs/12074196292/job/33671746482#step:5:199) and it seems that `com.fasterxml.jackson` is downgraded from **2.17.2** to **2.13.5** (version in dependency of [Spring Boot 2.7.18](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies/2.7.18), cause of the problem ?). The annotation `READ_DATE_TIMESTAMPS_AS_NANOSECONDS` was included in version 2.15.

Best regards.

**Comment by timtebeek** [comment]
Thanks for the detailed analysis already @nicolasb29 ; Can't say I've heard of these issues before. Quickly glancing at recipes we seem to have this one: https://github.com/openrewrite/rewrite-migrate-java/blob/cd36280b91d497086e220e965f2af3106e786ebf/src/main/resources/META-INF/rewrite/jakarta-ee-9.yml#L805-L810
But I'm not yet sure if that factors in, as it sounds like you're referring to an issue running OpenRewrite, not an issue after running OpenRewrite, correct?

**Comment by nicolasb29** [comment]
Yes it's a problem while the task `rewriteRun` is running.

**Comment by shanman190** [comment]
So my guess is the Spring Dependency Management plugin is the cause of the issues. It utilizes a Gradle resolutionStrategy which forces the versions across _all_ Gradle configurations to the one that would come from the Spring Boot Gradle plugin (ie. org.springframework.boot:spring-boot-dependencies).

Ultimately this would have forced OpenRewrite's Jackson version to likely be different (in this case down).

**Comment by nicolasb29** [comment]
One solution is to force the dependencies like in this [PR](https://github.com/openrewrite/rewrite-gradle-plugin/pull/349). 
This solution will solve the problem with jackson annotatiosn, but maybe others problems can append with others dependencies.

**Comment by nicolasb29** [comment]
In this example, there is also a problem with [snake yaml](https://github.com/nicolasb29/testopenrewritejackson/actions/runs/12074196292/job/33671746482#step:6:150)

with errors like this [There were problems parsing](https://github.com/nicolasb29/testopenrewritejackson/actions/runs/12074196292/job/33671746482#step:6:467)

**Comment by nicolasb29** [comment]
Hi,

I think that you have to keep the detached configuration to resolve dependencies in isolated mode.

I have updated the [PR](https://github.com/openrewrite/rewrite-gradle-plugin/pull/349)
