### ISSUE TITLE
Problem with Quarkus/Gradle and Gradle Subprojects

### ISSUE THREAD

**Issue by DaveO-Home** [openrewrite/rewrite-gradle-plugin#361]
I'm just a user of Quarkus and not familiar with openrewrite.
 
See: https://github.com/DaveO-Home/gradle-subprojects-quarkus

also Quarkus issue: https://github.com/quarkusio/quarkus/issues/45238

**Comment by shanman190** [comment]
Closing this issue as completed, however the actual issue was upstream with Quarkus using an old version of the OpenRewrite Gradle initscript.
