### ISSUE TITLE
Isolate classpath/classloader for rewrite from other gradle plugins

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-gradle-plugin#40]
All gradle plugins included in the same build share the same classpath at runtime.
This can be problematic when plugins used in the same build depend on different versions of the same dependencies. We've persistently had issues with our dependency on jackson conflicting with other gradle plugins that also depend on jackson.

To resolve this, we should remove our compile-time dependencies on rewrite and instead construct a detached Gradle dependency configuration at runtime, resolve the rewrite dependencies there, and construct our own isolated classloader through which we load & use rewrite at runtime.

**Comment by jbrisbin** [comment]
I found a post about this from 2013 and since then there've been many posts saying something to the effect "future versions of Gradle will provide plugins isolated classloaders". I guess they meant 10 years into the future? :trollface: 🤷‍♂️
