### ISSUE TITLE
Expose option to fail build if `rewriteDryRun` fails

### ISSUE THREAD

**Issue by jbduncan** [openrewrite/rewrite-gradle-plugin#42]
At the moment, if one runs `gradle rewriteDryRun`, then it reports any code that hasn't been refactored.

However, I'd love for the build to fail if `rewriteDryRun` reports any such code, so that I know about it at CI time.

It seems to me that a good way forward would be to expose a flag in the extension that, when enabled, makes the build fail if a dry run reports any problems. It would be `false` by default to maintain backwards compatibility. So something like:

```kotlin
rewrite {
  activeRecipe("com.yourorg.TheRecipe")

  failOnBadDryRun = true
}
```

But I'm open to other ideas!

What do you think, Rewrite team?

**Comment by aegershman** [comment]
👍   right on, thank you for logging this. We'll circle back to you on this.

(for issue-management purposes, linking the equivalent `rewrite-maven-plugin` logged issue: https://github.com/openrewrite/rewrite-maven-plugin/issues/139)

**Comment by jbduncan** [comment]
To add to my first comment, I found yesterday that one can apparently workaround this by configuring CI to check if any of the task's warnings are logged: https://docs.openrewrite.org/reference/gradle-plugin-configuration#the-dryrun-task

But, of course, the advantage of having this issue solved is it would allow `rewriteDryRun` to fail even outside of CI. :)

**Comment by aegershman** [comment]
Hey @jbduncan with https://github.com/openrewrite/rewrite-gradle-plugin/releases/tag/v4.2.1 you can wire up this configuration to have `rewriteDryRun` throw an exception/non-zero exit code on any detected changes:

```kt
rewrite {
    failOnDryRunResults = true
}
```

I'll add it to the reference docs a bit later. I'm going to close out this issue, but feel free to comment on this or open a different issue otherwise 👍

**Comment by jbduncan** [comment]
@aegershman Wow, thank you for such a quick turnaround!

I can confirm that version 4.2.2 has a `failOnDryRunResults` flag and, when I enable it, then change the ordering of a couple of modifiers and apply [`org.openrewrite.java.cleanup.ModifierOrder`](org/openrewrite/java/cleanup/ModifierOrder.java), then it causes my build to fail.

:tada:
