### ISSUE TITLE
Consider consolidating 'discover' per-sourceset tasks into single tasks

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite-gradle-plugin#50]
In order to simplify execution and bring the gradle-plugin into alignment with how the maven-plugin and other services work, consider consolidating per-souceset tasks into single tasks.

**Comment by sambsnyd** [comment]
This is done as of this commit https://github.com/openrewrite/rewrite-gradle-plugin/commit/e68db89c09c7848a6c12aaa60469d594f1322287
