### ISSUE TITLE
Update Gradle plugin to work with modern versions of rewrite core libs, have behavioral parity with Maven plugin

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite-gradle-plugin#8]

**Comment by sambsnyd** [comment]
Fixed by the combined powers of https://github.com/openrewrite/rewrite-gradle-plugin/commit/2bbfd004806c694604c11851605eb7d330999044 and https://github.com/openrewrite/rewrite-gradle-plugin/commit/c733e47d4ae3d67419076abd911250713a7b542d
