### ISSUE TITLE
Re-evaluate plugin publishing name/id

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite-gradle-plugin#86]
Consider updating the generated name/id for `gradlePlugin` to set the metadata for `rewrite-gradle-plugin` to result in a GAV similar to Maven, e.g. `org.openrewrite.maven:rewrite-maven-plugin`, but for gradle; so, `org.openrewrite.gradle:rewrite-gradle-plugin`. Currently, the generated metadata for the `rewrite-gradle-plugin` results in referencing the plugin as `org.openrewrite.rewrite`. This is acceptable for gradle, but when publishing this to Maven, it results in gav coordinates of `org.openrewrite:plugin` (https://oss.sonatype.org/service/local/repositories/snapshots/content/org/openrewrite/plugin/maven-metadata.xml). And having to do something a little peculiar with `pluginManagement` when publishing snapshots:

```kts
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.namespace == "org.openrewrite") {
                useModule("org.openrewrite:plugin:${requested.version}")
            }
        }
    }
    ...
}
```

From https://github.com/openrewrite/rewrite-gradle-plugin/issues/84

**Comment by sambsnyd** [comment]
It's an unintentional consequence of the way that the plugin is built out of a subproject named "plugin". And it's incidental, not intentional, that it's setup that way. I'm fine with changing it, but I'm not sure if that would cause us any problems with publishing to the gradle plugin portal.
