### ISSUE TITLE
Add dependency configuration just for recipes, while retaining compileOny and testCompileOnly as valid sources

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-gradle-plugin#9]
rewrite-testing-frameworks takes a dependency on junit4 so that junit4 can be removed. But if people leave rewrite-testing-frameworks as a `compileOnly` or `testCompileOnly` dependency then junit4 will _always_ be on their class path. 

So this is issue is to add a new configuration just for recipes, call it "rewrite" or "rewriteRecipe" or something along those lines. 
No other configuration will inherit from that one so we wont have to worry about cluttering up any classpaths but our own.

We should still _also_ look at the compile-time dependencies since we have a longer term aspiration that framework/library authors package upgrade recipes inside their jars. For that to work recipes need to continue to be discoverable from the compile classpath.

**Comment by jkschneider** [comment]
Closing this for now, as it wouldn't seem that `rewrite-testing-frameworks` should require a compile only dependency for recipes if it is written carefully. Perhaps it makes sense to keep junit4 on the test compile classpath of it for unit testing these recipes, but that's it.
